# Generated by Django 5.2.5 on 2025-08-10 17:11

import apps.tools.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Tool Categories",
                "db_table": "tools_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.JSONField(
                        default=dict, help_text="AI-generated structured description"
                    ),
                ),
                (
                    "manual_description",
                    models.TextField(
                        blank=True, help_text="Manual description override"
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("year_purchased", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField(help_text="Tool's latitude")),
                ("longitude", models.FloatField(help_text="Tool's longitude")),
                (
                    "address",
                    models.CharField(
                        help_text="Human-readable address", max_length=255
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "max_loan_days",
                    models.PositiveIntegerField(
                        default=7,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("ai_description_generated", models.BooleanField(default=False)),
                (
                    "ai_processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_tools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tools.toolcategory",
                    ),
                ),
            ],
            options={
                "db_table": "tools_tool",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.tools.models.tool_image_path),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("ai_analyzed", models.BooleanField(default=False)),
                ("ai_tags", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "db_table": "tools_photo",
                "ordering": ["-is_primary", "uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["is_available"], name="tools_tool_is_avai_2853b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["category"], name="tools_tool_categor_28a532_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(fields=["owner"], name="tools_tool_owner_i_b18b6a_idx"),
        ),
    ]
