"""AI-powered tool analysis endpoints."""

import base64
import json
import logging
from typing import Optional

import anthropic
from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status
from pydantic import BaseModel
from slowapi import Limiter
from slowapi.util import get_remote_address

from wippestoolen.app.api.v1.dependencies import get_current_active_user
from wippestoolen.app.core.config import settings
from wippestoolen.app.models.user import User

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ai", tags=["AI"])

limiter = Limiter(key_func=get_remote_address)

_ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/png", "image/webp"}
_MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB

_ANALYSIS_PROMPT = """Analyze this tool photo and return a JSON object with the following fields:

- title: string (German, descriptive name, e.g. "Bosch GSR 18V-55 Akkubohrschrauber")
- brand: string or null (manufacturer name, null if unknown)
- model: string or null (model number or name, null if unknown)
- category_slug: string (exactly one of: "elektrowerkzeuge", "handwerkzeuge", "garten", "haushalt", "fahrzeuge", "sport", "elektronik", "reinigung")
- condition: string (exactly one of: "excellent", "good", "fair", "poor")
- description: string (German, 2-3 sentences describing the tool, its typical use cases, and any visible features)
- safety_notes: string or null (German, relevant safety tips for this tool type; null if not applicable)

Respond ONLY with valid JSON. No markdown, no code fences, no explanation."""


class ToolAnalysisResponse(BaseModel):
    """Structured response from AI tool photo analysis."""

    title: str
    brand: Optional[str] = None
    model: Optional[str] = None
    category_slug: str
    condition: str
    description: str
    safety_notes: Optional[str] = None


@router.post(
    "/analyze-photo",
    response_model=ToolAnalysisResponse,
    status_code=status.HTTP_200_OK,
    summary="Analyze a tool photo with AI",
    description=(
        "Upload a tool photo to receive structured metadata suggestions "
        "generated by Claude Vision. Rate limited to 5 requests per minute per user."
    ),
)
@limiter.limit("5/minute")
async def analyze_tool_photo(
    request: Request,
    file: UploadFile = File(..., description="Tool image (JPEG, PNG, or WebP, max 5 MB)"),
    current_user: User = Depends(get_current_active_user),
) -> ToolAnalysisResponse:
    """
    Analyze a tool photo using Claude Haiku Vision and return structured metadata.

    The endpoint reads the uploaded image, encodes it as base64, and sends it to
    the Anthropic API. The model returns a JSON object with title, brand, model,
    category, condition, description, and safety notes – all in German where
    applicable.

    Args:
        file: Uploaded image file (JPEG, PNG, or WebP)
        current_user: Current authenticated and active user

    Returns:
        ToolAnalysisResponse: Structured tool metadata extracted from the photo

    Raises:
        HTTPException 422: If the file is larger than 5 MB or has an unsupported type
        HTTPException 503: If the Anthropic API key is not configured
        HTTPException 502: If the Claude API call fails or returns unparseable JSON
    """
    # Guard: API key must be present
    if not settings.ANTHROPIC_API_KEY:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI analysis is not available: ANTHROPIC_API_KEY is not configured.",
        )

    # Validate content type — fall back to extension-based detection
    content_type = file.content_type or ""
    if content_type not in _ALLOWED_IMAGE_TYPES:
        # Try to infer from filename
        filename = (file.filename or "").lower()
        if filename.endswith(".png"):
            content_type = "image/png"
        elif filename.endswith(".webp"):
            content_type = "image/webp"
        elif filename.endswith((".jpg", ".jpeg", ".heic")):
            content_type = "image/jpeg"
        else:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=(
                    f"Unsupported image type '{file.content_type}'. "
                    "Accepted types: image/jpeg, image/png, image/webp."
                ),
            )

    # Read file bytes and enforce size limit
    image_bytes = await file.read()
    if len(image_bytes) > _MAX_FILE_SIZE:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Image exceeds the maximum allowed size of 5 MB.",
        )

    # Encode to base64
    image_b64 = base64.standard_b64encode(image_bytes).decode("utf-8")

    # Map FastAPI content_type to Anthropic media_type literal
    media_type_map = {
        "image/jpeg": "image/jpeg",
        "image/png": "image/png",
        "image/webp": "image/webp",
    }
    media_type = media_type_map[content_type]

    # Call Claude Haiku Vision
    try:
        client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)
        message = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image",
                            "source": {
                                "type": "base64",
                                "media_type": media_type,
                                "data": image_b64,
                            },
                        },
                        {
                            "type": "text",
                            "text": _ANALYSIS_PROMPT,
                        },
                    ],
                }
            ],
        )
    except anthropic.APIError:
        logger.exception(
            "Claude API call failed for user %s during tool photo analysis",
            current_user.id,
        )
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI analysis failed: upstream API error. Please try again later.",
        )

    # Extract and parse JSON from the model response
    raw_text = message.content[0].text if message.content else ""
    try:
        payload = json.loads(raw_text)
        return ToolAnalysisResponse(**payload)
    except (json.JSONDecodeError, ValueError, TypeError):
        logger.exception(
            "Failed to parse Claude response for user %s. Raw response: %r",
            current_user.id,
            raw_text,
        )
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI analysis returned an unexpected response format. Please try again.",
        )
